namespace CMISProject.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class init : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.User", "CreatedByUserId", "dbo.User");
            DropForeignKey("dbo.Group", "CreateByUserId", "dbo.User");
            DropForeignKey("dbo.Message", "UserId", "dbo.User");
            DropForeignKey("dbo.Resource", "UserId", "dbo.User");
            DropForeignKey("dbo.InactiveUser", "UserId", "dbo.User");
            DropForeignKey("dbo.CustomGroupProperty", "GroupId", "dbo.Group");
            DropForeignKey("dbo.CustomUserProperty", "UserId", "dbo.User");
            DropForeignKey("dbo.ExamMarkSheet", "UserId", "dbo.User");
            DropForeignKey("dbo.Subject", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Subject", "SubjectTeacherId", "dbo.User");
            DropForeignKey("dbo.ExamMarkSheet", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.ExamRank", "UserId", "dbo.User");
            DropForeignKey("dbo.Faculty", "UserId", "dbo.User");
            DropForeignKey("dbo.GroupMessage", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupMessage", "MessageId", "dbo.Message");
            DropForeignKey("dbo.GroupPermission", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupPermission", "PermissionId", "dbo.Permission");
            DropForeignKey("dbo.GroupResource", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Resource", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.GroupResource", "ResourceId", "dbo.Resource");
            DropForeignKey("dbo.Routine", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Routine", "UserId", "dbo.User");
            DropForeignKey("dbo.UserMessage", "MessageId", "dbo.Message");
            DropForeignKey("dbo.UserMessage", "UserId", "dbo.User");
            DropForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permission");
            DropForeignKey("dbo.UserPermission", "UserId", "dbo.User");
            DropForeignKey("dbo.UserResource", "ResourceId", "dbo.Resource");
            DropForeignKey("dbo.UserResource", "UserId", "dbo.User");
            DropIndex("dbo.User", new[] { "CreatedByUserId" });
            DropIndex("dbo.Group", new[] { "CreateByUserId" });
            DropIndex("dbo.Message", new[] { "UserId" });
            DropIndex("dbo.Resource", new[] { "UserId" });
            DropIndex("dbo.InactiveUser", new[] { "UserId" });
            DropIndex("dbo.CustomGroupProperty", new[] { "GroupId" });
            DropIndex("dbo.CustomUserProperty", new[] { "UserId" });
            DropIndex("dbo.ExamMarkSheet", new[] { "UserId" });
            DropIndex("dbo.Subject", new[] { "GroupId" });
            DropIndex("dbo.Subject", new[] { "SubjectTeacherId" });
            DropIndex("dbo.ExamMarkSheet", new[] { "SubjectId" });
            DropIndex("dbo.ExamRank", new[] { "UserId" });
            DropIndex("dbo.Faculty", new[] { "UserId" });
            DropIndex("dbo.GroupMessage", new[] { "GroupId" });
            DropIndex("dbo.GroupMessage", new[] { "MessageId" });
            DropIndex("dbo.GroupPermission", new[] { "GroupId" });
            DropIndex("dbo.GroupPermission", new[] { "PermissionId" });
            DropIndex("dbo.GroupResource", new[] { "GroupId" });
            DropIndex("dbo.Resource", new[] { "SubjectId" });
            DropIndex("dbo.GroupResource", new[] { "ResourceId" });
            DropIndex("dbo.Routine", new[] { "GroupId" });
            DropIndex("dbo.Routine", new[] { "UserId" });
            DropIndex("dbo.UserMessage", new[] { "MessageId" });
            DropIndex("dbo.UserMessage", new[] { "UserId" });
            DropIndex("dbo.UserPermission", new[] { "PermissionId" });
            DropIndex("dbo.UserPermission", new[] { "UserId" });
            DropIndex("dbo.UserResource", new[] { "ResourceId" });
            DropIndex("dbo.UserResource", new[] { "UserId" });
            CreateTable(
                "dbo.GroupsUsers",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        GroupId = c.Int(nullable: false),
                        UserId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Group", t => t.GroupId, cascadeDelete: true)
                .ForeignKey("dbo.User", t => t.UserId, cascadeDelete: true)
                .Index(t => t.GroupId)
                .Index(t => t.UserId);
            
            AddColumn("dbo.Admin", "OrganizationName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Admin", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Admin", "CreatedBy", c => c.String());
            AddColumn("dbo.Admin", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Admin", "ModifiedBy", c => c.String());
            AddColumn("dbo.Admin", "PhoneNumbers", c => c.String());
            AddColumn("dbo.Group", "Password", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Group", "CreatedBy", c => c.String());
            AddColumn("dbo.Group", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Group", "ModifiedBy", c => c.String());
            AddColumn("dbo.User", "CreatedBy", c => c.String());
            AddColumn("dbo.User", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.User", "ModifiedBy", c => c.String());
            AddColumn("dbo.User", "PhoneNumber", c => c.String());
            AddColumn("dbo.Message", "CreatedBy", c => c.String());
            AddColumn("dbo.Message", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Message", "ModifiedBy", c => c.String());
            AddColumn("dbo.Permission", "PermissionName", c => c.String());
            AddColumn("dbo.Permission", "PermissionDescription", c => c.String());
            AddColumn("dbo.Resource", "UploadedBy", c => c.String());
            AddColumn("dbo.Resource", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Resource", "ModifiedBy", c => c.String());
            AddColumn("dbo.InactiveUser", "InactivatedBy", c => c.String());
            AddColumn("dbo.InactiveUser", "InactivatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Routine", "IssuedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Routine", "IssuedBy", c => c.String());
            AddColumn("dbo.Routine", "ModifiedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Routine", "ModifiedBy", c => c.String());
            AlterColumn("dbo.User", "UserId", c => c.Int(nullable: false, identity: true));
            CreateIndex("dbo.CustomGroupProperty", "GroupId");
            CreateIndex("dbo.CustomUserProperty", "UserId");
            CreateIndex("dbo.ExamMarkSheet", "UserId");
            CreateIndex("dbo.Subject", "GroupId");
            CreateIndex("dbo.Subject", "SubjectTeacherId");
            CreateIndex("dbo.ExamMarkSheet", "SubjectId");
            CreateIndex("dbo.ExamRank", "UserId");
            CreateIndex("dbo.Faculty", "UserId");
            CreateIndex("dbo.GroupMessage", "GroupId");
            CreateIndex("dbo.GroupMessage", "MessageId");
            CreateIndex("dbo.GroupPermission", "GroupId");
            CreateIndex("dbo.GroupPermission", "PermissionId");
            CreateIndex("dbo.GroupResource", "GroupId");
            CreateIndex("dbo.Resource", "SubjectId");
            CreateIndex("dbo.GroupResource", "ResourceId");
            CreateIndex("dbo.Routine", "GroupId");
            CreateIndex("dbo.Routine", "UserId");
            CreateIndex("dbo.UserMessage", "MessageId");
            CreateIndex("dbo.UserMessage", "UserId");
            CreateIndex("dbo.UserPermission", "PermissionId");
            CreateIndex("dbo.UserPermission", "UserId");
            CreateIndex("dbo.UserResource", "ResourceId");
            CreateIndex("dbo.UserResource", "UserId");
            AddForeignKey("dbo.CustomGroupProperty", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.CustomUserProperty", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.ExamMarkSheet", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Subject", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.Subject", "SubjectTeacherId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.ExamMarkSheet", "SubjectId", "dbo.Subject", "SubjectId", cascadeDelete: true);
            AddForeignKey("dbo.ExamRank", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Faculty", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.GroupMessage", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.GroupMessage", "MessageId", "dbo.Message", "MessageId", cascadeDelete: true);
            AddForeignKey("dbo.GroupPermission", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.GroupPermission", "PermissionId", "dbo.Permission", "PermissionId", cascadeDelete: true);
            AddForeignKey("dbo.GroupResource", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.Resource", "SubjectId", "dbo.Subject", "SubjectId", cascadeDelete: true);
            AddForeignKey("dbo.GroupResource", "ResourceId", "dbo.Resource", "ResourceId", cascadeDelete: true);
            AddForeignKey("dbo.Routine", "GroupId", "dbo.Group", "GroupId", cascadeDelete: true);
            AddForeignKey("dbo.Routine", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserMessage", "MessageId", "dbo.Message", "MessageId", cascadeDelete: true);
            AddForeignKey("dbo.UserMessage", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permission", "PermissionId", cascadeDelete: true);
            AddForeignKey("dbo.UserPermission", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserResource", "ResourceId", "dbo.Resource", "ResourceId", cascadeDelete: true);
            AddForeignKey("dbo.UserResource", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            DropColumn("dbo.Admin", "FirstName");
            DropColumn("dbo.Admin", "MiddleName");
            DropColumn("dbo.Admin", "LastName");
            DropColumn("dbo.Group", "CreateByUserId");
            DropColumn("dbo.User", "CreatedByUserId");
            DropColumn("dbo.Message", "UserId");
            DropColumn("dbo.Permission", "Perm");
            DropColumn("dbo.Resource", "UserId");
            DropColumn("dbo.InactiveUser", "UserId");
            DropColumn("dbo.InactiveUser", "InactiveDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.InactiveUser", "InactiveDate", c => c.String(nullable: false));
            AddColumn("dbo.InactiveUser", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.Resource", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.Permission", "Perm", c => c.String());
            AddColumn("dbo.Message", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.User", "CreatedByUserId", c => c.Int(nullable: false));
            AddColumn("dbo.Group", "CreateByUserId", c => c.Int(nullable: false));
            AddColumn("dbo.Admin", "LastName", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Admin", "MiddleName", c => c.String(maxLength: 20));
            AddColumn("dbo.Admin", "FirstName", c => c.String(nullable: false, maxLength: 20));
            DropForeignKey("dbo.UserResource", "UserId", "dbo.User");
            DropForeignKey("dbo.UserResource", "ResourceId", "dbo.Resource");
            DropForeignKey("dbo.UserPermission", "UserId", "dbo.User");
            DropForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permission");
            DropForeignKey("dbo.UserMessage", "UserId", "dbo.User");
            DropForeignKey("dbo.UserMessage", "MessageId", "dbo.Message");
            DropForeignKey("dbo.Routine", "UserId", "dbo.User");
            DropForeignKey("dbo.Routine", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupResource", "ResourceId", "dbo.Resource");
            DropForeignKey("dbo.Resource", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.GroupResource", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupPermission", "PermissionId", "dbo.Permission");
            DropForeignKey("dbo.GroupPermission", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupMessage", "MessageId", "dbo.Message");
            DropForeignKey("dbo.GroupMessage", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Faculty", "UserId", "dbo.User");
            DropForeignKey("dbo.ExamRank", "UserId", "dbo.User");
            DropForeignKey("dbo.ExamMarkSheet", "SubjectId", "dbo.Subject");
            DropForeignKey("dbo.Subject", "SubjectTeacherId", "dbo.User");
            DropForeignKey("dbo.Subject", "GroupId", "dbo.Group");
            DropForeignKey("dbo.ExamMarkSheet", "UserId", "dbo.User");
            DropForeignKey("dbo.CustomUserProperty", "UserId", "dbo.User");
            DropForeignKey("dbo.CustomGroupProperty", "GroupId", "dbo.Group");
            DropForeignKey("dbo.GroupsUsers", "UserId", "dbo.User");
            DropForeignKey("dbo.GroupsUsers", "GroupId", "dbo.Group");
            DropIndex("dbo.UserResource", new[] { "UserId" });
            DropIndex("dbo.UserResource", new[] { "ResourceId" });
            DropIndex("dbo.UserPermission", new[] { "UserId" });
            DropIndex("dbo.UserPermission", new[] { "PermissionId" });
            DropIndex("dbo.UserMessage", new[] { "UserId" });
            DropIndex("dbo.UserMessage", new[] { "MessageId" });
            DropIndex("dbo.Routine", new[] { "UserId" });
            DropIndex("dbo.Routine", new[] { "GroupId" });
            DropIndex("dbo.GroupResource", new[] { "ResourceId" });
            DropIndex("dbo.Resource", new[] { "SubjectId" });
            DropIndex("dbo.GroupResource", new[] { "GroupId" });
            DropIndex("dbo.GroupPermission", new[] { "PermissionId" });
            DropIndex("dbo.GroupPermission", new[] { "GroupId" });
            DropIndex("dbo.GroupMessage", new[] { "MessageId" });
            DropIndex("dbo.GroupMessage", new[] { "GroupId" });
            DropIndex("dbo.Faculty", new[] { "UserId" });
            DropIndex("dbo.ExamRank", new[] { "UserId" });
            DropIndex("dbo.ExamMarkSheet", new[] { "SubjectId" });
            DropIndex("dbo.Subject", new[] { "SubjectTeacherId" });
            DropIndex("dbo.Subject", new[] { "GroupId" });
            DropIndex("dbo.ExamMarkSheet", new[] { "UserId" });
            DropIndex("dbo.CustomUserProperty", new[] { "UserId" });
            DropIndex("dbo.CustomGroupProperty", new[] { "GroupId" });
            DropIndex("dbo.GroupsUsers", new[] { "UserId" });
            DropIndex("dbo.GroupsUsers", new[] { "GroupId" });
            AlterColumn("dbo.User", "UserId", c => c.Int(nullable: false));
            DropColumn("dbo.Routine", "ModifiedBy");
            DropColumn("dbo.Routine", "ModifiedDate");
            DropColumn("dbo.Routine", "IssuedBy");
            DropColumn("dbo.Routine", "IssuedDate");
            DropColumn("dbo.InactiveUser", "InactivatedDate");
            DropColumn("dbo.InactiveUser", "InactivatedBy");
            DropColumn("dbo.Resource", "ModifiedBy");
            DropColumn("dbo.Resource", "ModifiedDate");
            DropColumn("dbo.Resource", "UploadedBy");
            DropColumn("dbo.Permission", "PermissionDescription");
            DropColumn("dbo.Permission", "PermissionName");
            DropColumn("dbo.Message", "ModifiedBy");
            DropColumn("dbo.Message", "ModifiedDate");
            DropColumn("dbo.Message", "CreatedBy");
            DropColumn("dbo.User", "PhoneNumber");
            DropColumn("dbo.User", "ModifiedBy");
            DropColumn("dbo.User", "ModifiedDate");
            DropColumn("dbo.User", "CreatedBy");
            DropColumn("dbo.Group", "ModifiedBy");
            DropColumn("dbo.Group", "ModifiedDate");
            DropColumn("dbo.Group", "CreatedBy");
            DropColumn("dbo.Group", "Password");
            DropColumn("dbo.Admin", "PhoneNumbers");
            DropColumn("dbo.Admin", "ModifiedBy");
            DropColumn("dbo.Admin", "ModifiedDate");
            DropColumn("dbo.Admin", "CreatedBy");
            DropColumn("dbo.Admin", "CreatedDate");
            DropColumn("dbo.Admin", "OrganizationName");
            DropTable("dbo.GroupsUsers");
            CreateIndex("dbo.UserResource", "UserId");
            CreateIndex("dbo.UserResource", "ResourceId");
            CreateIndex("dbo.UserPermission", "UserId");
            CreateIndex("dbo.UserPermission", "PermissionId");
            CreateIndex("dbo.UserMessage", "UserId");
            CreateIndex("dbo.UserMessage", "MessageId");
            CreateIndex("dbo.Routine", "UserId");
            CreateIndex("dbo.Routine", "GroupId");
            CreateIndex("dbo.GroupResource", "ResourceId");
            CreateIndex("dbo.Resource", "SubjectId");
            CreateIndex("dbo.GroupResource", "GroupId");
            CreateIndex("dbo.GroupPermission", "PermissionId");
            CreateIndex("dbo.GroupPermission", "GroupId");
            CreateIndex("dbo.GroupMessage", "MessageId");
            CreateIndex("dbo.GroupMessage", "GroupId");
            CreateIndex("dbo.Faculty", "UserId");
            CreateIndex("dbo.ExamRank", "UserId");
            CreateIndex("dbo.ExamMarkSheet", "SubjectId");
            CreateIndex("dbo.Subject", "SubjectTeacherId");
            CreateIndex("dbo.Subject", "GroupId");
            CreateIndex("dbo.ExamMarkSheet", "UserId");
            CreateIndex("dbo.CustomUserProperty", "UserId");
            CreateIndex("dbo.CustomGroupProperty", "GroupId");
            CreateIndex("dbo.InactiveUser", "UserId");
            CreateIndex("dbo.Resource", "UserId");
            CreateIndex("dbo.Message", "UserId");
            CreateIndex("dbo.Group", "CreateByUserId");
            CreateIndex("dbo.User", "CreatedByUserId");
            AddForeignKey("dbo.UserResource", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.UserResource", "ResourceId", "dbo.Resource", "ResourceId");
            AddForeignKey("dbo.UserPermission", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.UserPermission", "PermissionId", "dbo.Permission", "PermissionId");
            AddForeignKey("dbo.UserMessage", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.UserMessage", "MessageId", "dbo.Message", "MessageId");
            AddForeignKey("dbo.Routine", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.Routine", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.GroupResource", "ResourceId", "dbo.Resource", "ResourceId");
            AddForeignKey("dbo.Resource", "SubjectId", "dbo.Subject", "SubjectId");
            AddForeignKey("dbo.GroupResource", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.GroupPermission", "PermissionId", "dbo.Permission", "PermissionId");
            AddForeignKey("dbo.GroupPermission", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.GroupMessage", "MessageId", "dbo.Message", "MessageId");
            AddForeignKey("dbo.GroupMessage", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.Faculty", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.ExamRank", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.ExamMarkSheet", "SubjectId", "dbo.Subject", "SubjectId");
            AddForeignKey("dbo.Subject", "SubjectTeacherId", "dbo.User", "UserId");
            AddForeignKey("dbo.Subject", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.ExamMarkSheet", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.CustomUserProperty", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.CustomGroupProperty", "GroupId", "dbo.Group", "GroupId");
            AddForeignKey("dbo.InactiveUser", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.Resource", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.Message", "UserId", "dbo.User", "UserId");
            AddForeignKey("dbo.Group", "CreateByUserId", "dbo.User", "UserId");
            AddForeignKey("dbo.User", "CreatedByUserId", "dbo.User", "UserId");
        }
    }
}
